### ISSUE TITLE
手机正常使用，但是电脑端使用就无法访问

### ISSUE THREAD

**Issue by 493Arceus** [ssrpanel/shadowsocksr#13]
ssr日志如下，panel里已设置账号useage四项都有勾选，但目前测试，就手机可以正常使用，而电脑不可以
`[INFO] asyncdns.py:287(__init__) black_hostname_list init as : []
[INFO] asyncdns.py:335(_parse_resolv) dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
[INFO] shell.py:74(log_shadowsocks_version) ShadowsocksR SSRR 3.2.2 2018-05-22
[INFO] db_transfer.py:251(thread_db) current process RLIMIT_NOFILE resource: soft 1000000 hard 1000000
[INFO] db_transfer.py:381(pull_db_all_user) pull user from data is finished!
[INFO] tcprelay.py:643(_handle_stage_addr) TCP request www.baidu.com:80 by user 43119
[INFO] tcprelay.py:794(_handle_dns_resolved) TCP connecting www.baidu.com(104.193.88.77):80 from 173.82.***.***:59641 by user 43119
[INFO] udprelay.py:478(_handle_server_dns_resolved) UDP data to 114.114.114.114(114.114.114.114):53 from 0.0.0.0:57193 by user 43119
[INFO] tcprelay.py:643(_handle_stage_addr) TCP request www.baidu.com:80 by user 43119
[INFO] tcprelay.py:794(_handle_dns_resolved) TCP connecting www.baidu.com(104.193.88.77):80 from 173.82.153.226:48843 by user 43119
`

**Comment by rc452860** [comment]
这个日志是正常的啊

**Comment by 493Arceus** [comment]
![qq 20181203195902](https://user-images.githubusercontent.com/17383497/49372553-0a6cd780-f736-11e8-812e-1f1e31799a33.png)
![qq 20181203195938](https://user-images.githubusercontent.com/17383497/49372555-0b056e00-f736-11e8-971c-f3194328dc2d.jpg)
配置一样，都是通过酸酸乳链接导入的

**Comment by rc452860** [comment]
感觉没什么问题换个电脑测试一下呢.之前也有人出现过这种情况结果是自己电脑的问题.

**Comment by 493Arceus** [comment]
非常感谢，测试了一下是SSTAP的问题，用酸酸乳就没问题了
