### ISSUE TITLE
No module named peewee

### ISSUE THREAD

**Issue by yanygm** [ssrpanel/shadowsocksr#18]
[INFO] util.py:94(find_library) loading libsodium from libsodium.so.23
[INFO] asyncdns.py:287(__init__) black_hostname_list init as : []
[INFO] asyncdns.py:335(_parse_resolv) dns server: [('169.254.169.254', 53)]
[INFO] shell.py:74(log_shadowsocks_version) ShadowsocksR SSRR 3.2.2 2018-05-22
[INFO] db_transfer.py:251(thread_db) current process RLIMIT_NOFILE resource: soft 1000000 hard 1000000
[INFO] db_transfer.py:381(pull_db_all_user) pull user from data is finished!
IPv6 support
Traceback (most recent call last):
  File "server.py", line 25, in <module>
    import db_transfer
  File "/root/shadowsocksr/db_transfer.py", line 13, in <module>
    from database import *
  File "/root/shadowsocksr/database/__init__.py", line 9, in <module>
    from peewee import *
ImportError: No module named peewee

**Comment by rc452860** [comment]
pip install -r requestment.txt

**Comment by yanygm** [comment]
> pip install -r requestment.txt

好像是环境问题，我把“.bashrc”的内容写到"profile"，才行

**Comment by rc452860** [comment]
如果您已经解决了的话这个iussue我就关了
