### ISSUE TITLE
状态老是提示“宕机”，可以正常连接

### ISSUE THREAD

**Issue by yanygm** [ssrpanel/shadowsocksr#19]
![image](https://user-images.githubusercontent.com/17066245/51437476-e0697780-1cd9-11e9-8565-f9190a0ec03a.png)
时区和时间都是统一的
SSR线路可以正常使用

**Comment by rc452860** [comment]
最新版本吗？

**Comment by yanygm** [comment]
> 最新版本吗？

是的啊

**Comment by rc452860** [comment]
哦这个版本最近没在维护。我在弄go语言版本的。这个问题要问一下 @ssrpanel

**Comment by yanygm** [comment]
> 哦这个版本最近没在维护。我在弄go语言版本的。这个问题要问一下 @ssrpanel

Vnet？，我去用下试试

**Comment by yanygm** [comment]
@rc452860 Vnet怎么在SSRPanel中添加线路？

**Comment by yanygm** [comment]
![image](https://user-images.githubusercontent.com/17066245/51450837-47843c00-1d6d-11e9-80b0-579a578cb8c7.png)
可以，很厉害

**Comment by yanygm** [comment]
关闭这个问题吧

**Comment by rc452860** [comment]
as your wish.
