### ISSUE TITLE
数据库链接报错，解决不了

### ISSUE THREAD

**Issue by lzmfor** [ssrpanel/shadowsocksr#2]
使用这个一键脚本搭SSR。。配合SSRPanel：wget -N --no-check-certificate https://raw.githubusercontent.com/ssrpanel/ssrpanel/master/server/deploy_ssr.sh;chmod +x deploy_ssr.sh;./deploy_ssr.sh

python server.py	的时候数据库报错，如下：
![s_09-01-36_2018-05-02](https://user-images.githubusercontent.com/11819708/39500586-2b631140-4de8-11e8-8467-8b4afe4ee053.png)

尝试了好几次。防火墙什么的检查过了
然后试了其他手动搭建的，，结果可以。。
谢谢！

**Comment by lidingrong** [comment]
确实是，新安装的服务器都是这个问题，启动不了

**Comment by lzmfor** [comment]
手动布置可以。后台负载也正常。不会宕机。估计一键脚本问题

**Comment by ssrpanel** [comment]
用setup_cymysql2.sh

**Comment by ssrpanel** [comment]
因为自动安装cymysql是读取最新的cymysql，最新版本不支持5.6及以下的mysql数据库
