### ISSUE TITLE
ip没有上报问题

### ISSUE THREAD

**Issue by happy4041** [ssrpanel/shadowsocksr#21]
您好，

今天我搭建了最近ssrpanel的版本以及使用了现在这个后端，后端使用的是https://github.com/ssrpanel/shadowsocksr/archive/master.zip 这个包，但是这个后端不知道为什么没有上报ip，我的ss_node_ip表一直是空的，流量之类的其他东西都有上报。

顺便说一下，我的python版本是2.7.12，不知道是不是这个原因，暂时没在3.x版本使用过。

希望能解决，谢谢大佬！

**Comment by ssrpanel** [comment]
已放弃维护，全面转向vnet
